-- 電信門市銷售助理系統 - Oracle 資料庫 Schema
-- 建立日期: 2025-10-13
-- 說明: 包含員工管理、客戶資料、續約記錄、統計資料等表格

-- ========================================
-- 1. 門市資料表
-- ========================================
CREATE TABLE stores (
    store_id VARCHAR2(20) PRIMARY KEY,
    store_name VARCHAR2(100) NOT NULL,
    store_address VARCHAR2(300),
    store_phone VARCHAR2(20),
    region VARCHAR2(50),
    is_active NUMBER(1) DEFAULT 1,
    created_at DATE DEFAULT SYSDATE,
    updated_at DATE DEFAULT SYSDATE
);

-- ========================================
-- 2. 員工資料表
-- ========================================
CREATE TABLE staff (
    staff_id VARCHAR2(20) PRIMARY KEY,
    staff_code VARCHAR2(10) UNIQUE NOT NULL,
    name VARCHAR2(50) NOT NULL,
    role VARCHAR2(20) NOT NULL CHECK (role IN ('Sales', 'Manager', 'Admin')),
    store_id VARCHAR2(20) NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    email VARCHAR2(100),
    phone VARCHAR2(20),
    is_active NUMBER(1) DEFAULT 1,
    created_at DATE DEFAULT SYSDATE,
    updated_at DATE DEFAULT SYSDATE,
    CONSTRAINT fk_staff_store FOREIGN KEY (store_id) REFERENCES stores(store_id)
);

-- ========================================
-- 3. 登入記錄表
-- ========================================
CREATE TABLE login_logs (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id VARCHAR2(20) NOT NULL,
    login_time DATE NOT NULL,
    logout_time DATE,
    ip_address VARCHAR2(45),
    user_agent VARCHAR2(500),
    session_duration NUMBER, -- 秒數
    created_at DATE DEFAULT SYSDATE,
    CONSTRAINT fk_login_staff FOREIGN KEY (staff_id) REFERENCES staff(staff_id)
);

-- ========================================
-- 4. 客戶資料表 (模擬)
-- ========================================
CREATE TABLE customers (
    customer_id VARCHAR2(20) PRIMARY KEY,
    id_number VARCHAR2(20) UNIQUE NOT NULL,
    name VARCHAR2(50) NOT NULL,
    phone VARCHAR2(20),
    email VARCHAR2(100),
    address VARCHAR2(300),
    is_company_customer NUMBER(1) DEFAULT 1,
    credit_rating VARCHAR2(10) DEFAULT 'GOOD',
    created_at DATE DEFAULT SYSDATE,
    updated_at DATE DEFAULT SYSDATE
);

-- ========================================
-- 5. 門號合約表 (模擬)
-- ========================================
CREATE TABLE phone_contracts (
    contract_id VARCHAR2(20) PRIMARY KEY,
    customer_id VARCHAR2(20) NOT NULL,
    phone_number VARCHAR2(20) UNIQUE NOT NULL,
    current_plan VARCHAR2(50),
    monthly_fee NUMBER(8,2),
    contract_start_date DATE,
    contract_end_date DATE,
    status VARCHAR2(20) DEFAULT 'ACTIVE',
    created_at DATE DEFAULT SYSDATE,
    updated_at DATE DEFAULT SYSDATE,
    CONSTRAINT fk_contract_customer FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);

-- ========================================
-- 6. 續約會話記錄表
-- ========================================
CREATE TABLE renewal_sessions (
    session_id VARCHAR2(50) PRIMARY KEY,
    staff_id VARCHAR2(20) NOT NULL,
    customer_id VARCHAR2(20),
    phone_number VARCHAR2(20),
    current_step VARCHAR2(30),
    session_data CLOB, -- JSON 格式的會話資料
    status VARCHAR2(20) DEFAULT 'IN_PROGRESS',
    is_sale_confirmed NUMBER(1) DEFAULT 0,
    total_amount NUMBER(10,2),
    created_at DATE DEFAULT SYSDATE,
    updated_at DATE DEFAULT SYSDATE,
    completed_at DATE,
    CONSTRAINT fk_session_staff FOREIGN KEY (staff_id) REFERENCES staff(staff_id),
    CONSTRAINT fk_session_customer FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);

-- ========================================
-- 7. AI 使用記錄表
-- ========================================
CREATE TABLE ai_usage_logs (
    usage_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id VARCHAR2(20) NOT NULL,
    session_id VARCHAR2(50),
    usage_type VARCHAR2(30) NOT NULL, -- 'chat', 'comparison', 'recommendation' etc.
    prompt_text CLOB,
    response_text CLOB,
    prompt_tokens NUMBER,
    completion_tokens NUMBER,
    total_tokens NUMBER,
    cost_amount NUMBER(10,6),
    created_at DATE DEFAULT SYSDATE,
    CONSTRAINT fk_ai_usage_staff FOREIGN KEY (staff_id) REFERENCES staff(staff_id)
);

-- ========================================
-- 8. 客服記錄表
-- ========================================
CREATE TABLE customer_service_logs (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id VARCHAR2(20) NOT NULL,
    customer_id VARCHAR2(20) NOT NULL,
    service_type VARCHAR2(30) NOT NULL, -- 'renewal', 'inquiry', 'complaint' etc.
    service_result VARCHAR2(30), -- 'completed', 'cancelled', 'pending'
    notes CLOB,
    service_duration NUMBER, -- 分鐘數
    created_at DATE DEFAULT SYSDATE,
    CONSTRAINT fk_service_staff FOREIGN KEY (staff_id) REFERENCES staff(staff_id),
    CONSTRAINT fk_service_customer FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);

-- ========================================
-- 9. 每日員工統計表 (彙總表)
-- ========================================
CREATE TABLE daily_staff_statistics (
    stat_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id VARCHAR2(20) NOT NULL,
    stat_date DATE NOT NULL,
    login_count NUMBER DEFAULT 0,
    total_login_duration NUMBER DEFAULT 0, -- 分鐘數
    customers_served NUMBER DEFAULT 0,
    sessions_started NUMBER DEFAULT 0,
    sessions_completed NUMBER DEFAULT 0,
    sales_confirmed NUMBER DEFAULT 0,
    ai_usage_count NUMBER DEFAULT 0,
    total_ai_tokens NUMBER DEFAULT 0,
    total_ai_cost NUMBER(10,6) DEFAULT 0,
    created_at DATE DEFAULT SYSDATE,
    updated_at DATE DEFAULT SYSDATE,
    CONSTRAINT fk_daily_stat_staff FOREIGN KEY (staff_id) REFERENCES staff(staff_id),
    CONSTRAINT uk_daily_stat_unique UNIQUE (staff_id, stat_date)
);

-- ========================================
-- 10. 促銷方案表 (模擬)
-- ========================================
CREATE TABLE promotions (
    promotion_id VARCHAR2(20) PRIMARY KEY,
    promotion_name VARCHAR2(100) NOT NULL,
    description CLOB,
    plan_type VARCHAR2(30),
    monthly_fee NUMBER(8,2),
    data_allowance VARCHAR2(50), -- "50GB", "Unlimited" etc.
    voice_minutes VARCHAR2(50),
    sms_count VARCHAR2(50),
    contract_months NUMBER,
    eligibility_rules CLOB, -- JSON 格式的資格規則
    is_active NUMBER(1) DEFAULT 1,
    start_date DATE,
    end_date DATE,
    created_at DATE DEFAULT SYSDATE,
    updated_at DATE DEFAULT SYSDATE
);

-- ========================================
-- 11. 手機裝置表 (模擬)
-- ========================================
CREATE TABLE devices (
    device_id VARCHAR2(20) PRIMARY KEY,
    device_name VARCHAR2(100) NOT NULL,
    brand VARCHAR2(50),
    model VARCHAR2(50),
    os_type VARCHAR2(20) CHECK (os_type IN ('Android', 'iOS')),
    price NUMBER(10,2),
    colors CLOB, -- JSON 陣列格式
    specifications CLOB, -- JSON 格式
    is_recommended NUMBER(1) DEFAULT 0,
    is_active NUMBER(1) DEFAULT 1,
    created_at DATE DEFAULT SYSDATE,
    updated_at DATE DEFAULT SYSDATE
);

-- ========================================
-- 建立索引
-- ========================================

-- 員工相關索引
CREATE INDEX idx_staff_code ON staff(staff_code);
CREATE INDEX idx_staff_store ON staff(store_id);
CREATE INDEX idx_staff_role ON staff(role);

-- 登入記錄索引
CREATE INDEX idx_login_staff_time ON login_logs(staff_id, login_time);

-- 客戶相關索引
CREATE INDEX idx_customer_id_number ON customers(id_number);
CREATE INDEX idx_contract_customer ON phone_contracts(customer_id);
CREATE INDEX idx_contract_phone ON phone_contracts(phone_number);

-- 續約會話索引
CREATE INDEX idx_session_staff ON renewal_sessions(staff_id);
CREATE INDEX idx_session_status ON renewal_sessions(status);
CREATE INDEX idx_session_created ON renewal_sessions(created_at);

-- AI 使用記錄索引
CREATE INDEX idx_ai_usage_staff ON ai_usage_logs(staff_id);
CREATE INDEX idx_ai_usage_created ON ai_usage_logs(created_at);

-- 統計相關索引
CREATE INDEX idx_daily_stat_date ON daily_staff_statistics(stat_date);
CREATE INDEX idx_service_log_staff ON customer_service_logs(staff_id);

-- ========================================
-- 建立序列 (如果需要)
-- ========================================

-- 可用於產生唯一 ID
CREATE SEQUENCE seq_customer_id START WITH 100000 INCREMENT BY 1;
CREATE SEQUENCE seq_contract_id START WITH 200000 INCREMENT BY 1;
CREATE SEQUENCE seq_promotion_id START WITH 300000 INCREMENT BY 1;
CREATE SEQUENCE seq_device_id START WITH 400000 INCREMENT BY 1;

-- ========================================
-- 註解
-- ========================================

-- 新增表格註解
COMMENT ON TABLE stores IS '門市資料表';
COMMENT ON TABLE staff IS '員工資料表';
COMMENT ON TABLE login_logs IS '登入記錄表';
COMMENT ON TABLE customers IS '客戶資料表';
COMMENT ON TABLE phone_contracts IS '門號合約表';
COMMENT ON TABLE renewal_sessions IS '續約會話記錄表';
COMMENT ON TABLE ai_usage_logs IS 'AI使用記錄表';
COMMENT ON TABLE customer_service_logs IS '客服記錄表';
COMMENT ON TABLE daily_staff_statistics IS '每日員工統計表';
COMMENT ON TABLE promotions IS '促銷方案表';
COMMENT ON TABLE devices IS '手機裝置表';

-- 重要欄位註解
COMMENT ON COLUMN staff.role IS '角色: Sales/Manager/Admin';
COMMENT ON COLUMN staff.password_hash IS 'bcrypt 雜湊後的密碼';
COMMENT ON COLUMN renewal_sessions.session_data IS 'JSON格式的會話狀態資料';
COMMENT ON COLUMN ai_usage_logs.usage_type IS 'AI使用類型: chat/comparison/recommendation';
COMMENT ON COLUMN daily_staff_statistics.total_login_duration IS '總登入時長(分鐘)';

COMMIT;